# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-bC36w6435fXS3ieD8dn9KhCTUAWaK3


"""

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk.corpus import stopwords

import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Embedding, Conv1D, GlobalMaxPooling1D, LSTM, Bidirectional,
    Dense, Dropout, Input, Concatenate, BatchNormalization, SpatialDropout1D
)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix
)
from sklearn.utils.class_weight import compute_class_weight
from scipy.stats import randint

from datasets import load_dataset
import plotly.express as px

"""## تحميل مجموعة البيانات"""

dataset_name = "Ahmed-Selem/Shifaa_Arabic_Medical_Consultations"

try:
    dataset = load_dataset(dataset_name)
    print(f"Successfully downloaded dataset: {dataset_name}")
    print(dataset)
except Exception as e:
    print(f"Error downloading dataset {dataset_name}: {e}")

"""## تحويل البيانات إلى DataFrame

هذا التحويل يسهل علينا:
- استكشاف البيانات (EDA)
- تنفيذ عمليات المعالجة المسبقة
- تحليل الأعمدة والقيم النصية


"""

df = dataset['train'].to_pandas()
print("Dataset converted to pandas DataFrame. Displaying the first 5 rows:")
display(df.head())

# Extract the main category from 'Hierarchical Diagnosis'
df['Main Category'] = df['Hierarchical Diagnosis'].apply(lambda x: x.split(' - ')[0] if isinstance(x, str) and ' - ' in x else x)

print("Added 'main category' column. Displaying the first 5 rows with the new column:")
display(df.head())

"""## استكشاف بنية مجموعة البيانات
في هذه الخطوة نقوم بفحص البنية العامة لمجموعة البيانات من خلال:
- معرفة عدد الصفوف (العينات)
- عدد الأعمدة (الميزات)
- أسماء الأعمدة المتوفرة


"""

print("Number of rows and columns in the dataset:")
print(df.shape)
print("\nColumns in the dataset:")
print(df.columns.tolist())

"""نلاحظ أن مجموعة البيانات تحتوي على 84,422 عينة و 8 أعمدة

## التحقق من القيم المفقودة
"""

print("Number of missing values in each column:")
print(df.isnull().sum())

"""تُظهر النتائج أن جميع الأعمدة خالية من القيم المفقودة  
مما يدل على جودة مجموعة البيانات ويغنينا عن تنفيذ خطوات معالجة خاصة بالقيم الناقصة.

## توزيع الفئات الطبية (Main Category)
"""

print("Distribution of Main Category:")
print(df['Main Category'].value_counts())

"""نلاحظ أن بعض التخصصات الطبية تحتوي على عدد كبير من الأسئلة مثل:
- أمراض النساء والولادة
- أمراض الباطنية والصدر

في حين أن تخصصات أخرى تحتوي على عدد أقل من العينات مثل:
- الطب البديل
- الجراحة العامة والتجميل

وهذا يشير إلى وجود عدم توازن نسبي بين الفئات

## التوزيع النسبي للفئات الطبية
"""

print("Percentage distribution of Main Category:")
print(df['Main Category'].value_counts(normalize=True) * 100)

"""نلاحظ أن أكبر فئة تمثل حوالي 17% من البيانات،  
بينما بعض الفئات تمثل أقل من 1% فقط.

هذا التفاوت يؤكد ضرورة الانتباه إلى مشكلة **Class Imbalance** أثناء مرحلة النمذجة.

## تحليل طول نصوص الأسئلة
في هذه الخطوة نقوم بتحليل طول الأسئلة الطبية من حيث:
- عدد المحارف (Character Length)
- عدد الكلمات (Word Length)
"""

df['question_char_length'] = df['Question'].apply(lambda x: len(str(x)))
df['question_word_length'] = df['Question'].apply(lambda x: len(str(x).split()))
print("Added character length and word length for each question.")
display(df[['Question', 'question_char_length', 'question_word_length']].head())

"""نلاحظ وجود تباين في أطوال الأسئلة،  
حيث تتراوح الأسئلة بين قصيرة نسبيًا وأخرى أطول تحتوي على شرح تفصيلي للحالة الطبية

## التحليل الإحصائي لأطوال نصوص الأسئلة
"""

print("Character length statistics:")
display(df['question_char_length'].describe())
print("Word length statistics:")
display(df['question_word_length'].describe())

"""نلاحظ أن:
- متوسط طول السؤال يقارب 587 محرفًا و 105 كلمة
- نصف الأسئلة تقريبًا تحتوي على أقل من 465 محرفًا و 83 كلمة
- توجد أسئلة طويلة جدًا تصل إلى أكثر من 1200 كلمة وقرابة 7000 محرف

يشير ذلك إلى وجود تفاوت كبير في أطوال الأسئلة

## التحقق من الأسئلة المكررة
"""

duplicate_count = df['Question'].duplicated().sum()
print(f"Number of duplicated questions: {duplicate_count}")

"""تم العثور على 29,212 سؤالا مكررا،  
وهو عدد كبير نسبيا مقارنة بحجم البيانات الكلي.

## تحليل الأسئلة المتطرفة (قصيرة جدًا وطويلة جدًا)
لفهم طبيعة البيانات بشكل أعمق، نقوم بعرض أمثلة على:
- الأسئلة القصيرة جدًا (أقل من 3 كلمات)
- الأسئلة الطويلة جدًا (أكثر من 50 كلمة)
"""

print("Examples of very short questions (less than 3 words):")
display(df[df['question_word_length'] < 3].head())
print("\nExamples of very long questions (more than 50 words):")
display(df[df['question_word_length'] > 50].head())

"""نلاحظ أن الأسئلة القصيرة جدا غير موجودة فعليًا،  
بينما الأسئلة الطويلة شائعة نسبيًا، وغالبًا ما تتضمن وصفًا تفصيليًا للحالة الطبية.
"""

fig = px.histogram(
    df,
    x='question_word_length',
    nbins=50,
    title='Distribution of Question Lengths (in words)',
    labels={'question_word_length': 'Number of words in question', 'count': 'Number of questions'},
    color_discrete_sequence=['skyblue']
)

fig.update_layout(
    bargap=0.05,
    xaxis=dict(title='Number of words in question'),
    yaxis=dict(title='Number of questions'),
    template='plotly_white'
)

fig.show()

"""#عدد الفئات داخل Hierarchical Diagnosis


"""

print("Number of unique hierarchical diagnoses:")
print(df['Hierarchical Diagnosis'].nunique())
print("\nExamples of diagnosis values:")
display(df['Hierarchical Diagnosis'].head(10))

"""نلاحظ وجود 585 تصنيفا هرميا مختلفا  
مما يعكس درجة عالية من التفصيل في التشخيص الطبي.

## تحليل التصنيفات الطبية الرئيسية (Main Category)
"""

print("Number of unique Main Category:")
print(df['Main Category'].nunique())
print("All unique Main Categories:")
display(df['Main Category'].unique())

"""نلاحظ أن عدد الفئات الطبية الرئيسية هو 16 فئة فقط  
وهو عدد مناسب لبناء نماذج تصنيف فعالة ومستقرة.


"""

category_counts = df['Main Category'].value_counts().reset_index()
category_counts.columns = ['Main Category', 'Count']
fig = px.bar(
    category_counts,
    x='Main Category',
    y='Count',
    title='Distribution of Main Categories',
    text='Count',
    color='Count',
    color_continuous_scale='Viridis')
fig.update_layout(
    xaxis_title="Main Category",
    yaxis_title="Number of Questions",
    xaxis_tickangle=-45)
fig.show()

"""## إزالة الأسئلة المكررة
الهدف من هذه الخطوة هو:
- تقليل التحيز في البيانات
- منع تكرار نفس العينة في التدريب والتقييم
- تحسين تعميم النموذج
"""

def remove_duplicates(df):
    before = len(df)
    df = df.drop_duplicates(subset='Question', keep='first')
    after = len(df)
    print(f"Removed {before - after} duplicated questions.")
    return df

df = remove_duplicates(df)

"""تمت إزالة 29,212 سؤالا مكررا"""

category_counts_cleaned = df['Main Category'].value_counts().reset_index()
category_counts_cleaned.columns = ['Main Category', 'Count']
fig = px.bar(
    category_counts_cleaned,
    x='Main Category',
    y='Count',
    title='Distribution of Main Categories (After Removing Duplicates)',
    text='Count',
    color='Count',
    color_continuous_scale='Viridis')
fig.update_layout(
    xaxis_title="Main Category",
    yaxis_title="Number of Questions",
    xaxis_tickangle=-45)
fig.show()

"""## تنظيف النصوص الطبية

في هذه الخطوة نقوم بتنظيف نصوص الأسئلة الطبية من العناصر غير المفيدة، مثل:
- الروابط الإلكترونية
- الرموز الخاصة غير العربية
- التكرار غير الضروري للفراغات

يهدف هذا التنظيف إلى تقليل الضجيج وتحسين جودة تمثيل النص.

"""

def clean_medical_text(text):
    if not isinstance(text, str):
        return text
    text = re.sub(r"http\S+|www.\S+", " ", text)
    text = re.sub(r"[^\w\s\u0600-\u06FF0-9]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['clean_question'] = df['Question'].apply(clean_medical_text)

"""## توحيد الكتابة العربية (Normalization)

نقوم بتوحيد هذه الأشكال إلى صيغة واحدة.

تشمل هذه الخطوة:
- توحيد الألف(أ, إ, آ → ا)
- تحويل (ى → ي)
- تحويل (ة → ه)
- إزالة التطويل (ـ)

يساعد ذلك في:
- تقليل حجم المفردات
- تحسين تمثيل الكلمات
- زيادة كفاءة النماذج الإحصائية والعميقة

"""

def normalize_arabic(text):
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ؤ", "و", text)
    text = re.sub("ئ", "ي", text)
    text = re.sub("ـ", "", text)
    return text

df['normalized_question'] = df['clean_question'].apply(normalize_arabic)
df[['clean_question','normalized_question']].head()

"""## إزالة كلمات التوقف

كلمات التوقف هي كلمات شائعة في اللغة (مثل: من، إلى، على)  
ولا تحمل غالبًا قيمة دلالية مهمة لعملية التصنيف.
"""

nltk.download('stopwords')
  arabic_stopwords = set(stopwords.words('arabic'))
  def remove_stopwords(text):
      words = text.split()
      words = [w for w in words if w not in arabic_stopwords]
      return " ".join(words)
  df['no_stopwords_question'] = df['normalized_question'].apply(remove_stopwords)

"""## إزالة الأسئلة القصيرة جدًا

بعض الأسئلة القصيرة جدًا (أقل من 3 كلمات)  
لا تحتوي على معلومات كافية لتحديد الاختصاص الطبي بدقة.

لذلك نقوم بحذف هذه الأسئلة من مجموعة البيانات.

"""

before = len(df)
df = df[df['no_stopwords_question'].apply(lambda x: len(x.split()) >= 3)]
after = len(df)
print(f"Removed {before - after} very short questions.")

"""تمت إزالة سؤال واحد فقط  
مما يدل على أن معظم الأسئلة تحتوي على وصف كافٍ للحالة الطبية.

## قص النصوص الطويلة

نظرًا لوجود أسئلة طويلة جدًا،  
نقوم بتحديد حد أقصى لطول السؤال بـ 250 كلمة.
"""

def trim_text(text, max_words=250):
    words = text.split()
    if len(words) > max_words:
        return " ".join(words[:max_words])
    return text
df['trimmed_question'] = df['no_stopwords_question'].apply(trim_text)

"""## 🏷️ ترميز الفئات (Label Encoding)

بما أن عمود(Main Category) عبارة عن نص عربي،
فإننا نحتاج لتحويله إلى أرقام حتى تتمكن النماذج من التعامل معه.
"""

label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['Main Category'])
df[['Main Category','label']].head()

"""## تقسيم البيانات إلى تدريب وتحقق واختبار

في هذه الخطوة نقوم بتقسيم البيانات إلى:
- 80% تدريب
- 10% تحقق (Validation)
- 10% اختبار (Test)

يتم التقسيم باستخدام **Stratified Sampling**  
لضمان الحفاظ على نفس توزيع الفئات في جميع المجموعات.

"""

train_df, temp_df = train_test_split(df, test_size=0.2, stratify=df['label'], random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.5, stratify=temp_df['label'], random_state=42)
print(train_df.shape, val_df.shape, test_df.shape)

"""## تحديد المدخلات والمخرجات

- المدخلات (X): نص السؤال بعد المعالجة (`trimmed_question`)
- المخرجات (y): التصنيف الطبي المرمّز (`label`)

"""

X_train = train_df['trimmed_question']
X_val = val_df['trimmed_question']
X_test = test_df['trimmed_question']

y_train = train_df['label']
y_val = val_df['label']
y_test = test_df['label']

"""### تحويل النصوص إلى TF-IDF Features

"""

tfidf = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.90,
    max_features=50000,
    token_pattern=r"(?u)\b\w+\b",
    lowercase=False,
    stop_words=None
)
X_train_tfidf = tfidf.fit_transform(X_train)
X_val_tfidf = tfidf.transform(X_val)
X_test_tfidf = tfidf.transform(X_test)
print("X_train_tfidf shape:", X_train_tfidf.shape)
print("X_val_tfidf shape:  ", X_val_tfidf.shape)
print("X_test_tfidf shape: ", X_test_tfidf.shape)

"""###  تحليل بعض ميزات TF-IDF

"""

feature_names = tfidf.get_feature_names_out()
print("Number of features:", len(feature_names))
print(feature_names[:20])
row0 = X_train_tfidf[0]
nz = row0.nonzero()[1]
top_n = sorted([(i, row0[0, i]) for i in nz], key=lambda x: x[1], reverse=True)[:15]
for idx, val in top_n:
    print(feature_names[idx], "-->", val)

"""عند استعراض بعض الميزات الأعلى وزنًا في أحد نصوص التدريب، لوحظ وجود:

- عبارات طبية دلالية مثل:
  - `اعاني مغص`
  - `مغص شديد`
  - `شرب اللبن`
- وبعض الكلمات أو العبارات العامة مثل:
  - `ذلك`
  - `وقد`

###  تدريب نموذج Logistic Regression (Baseline)

تم تدريب نموذج **Logistic Regression** بالإعدادات الافتراضية مع:

- `class_weight='balanced'`  
  لمعالجة عدم توازن الفئات.
"""

logreg = LogisticRegression(
    max_iter=300,
    class_weight='balanced',
    solver='liblinear',
    n_jobs=-1
)
logreg.fit(X_train_tfidf, y_train)
train_pred = logreg.predict(X_train_tfidf)
val_pred = logreg.predict(X_val_tfidf)
test_pred = logreg.predict(X_test_tfidf)

print("Train Accuracy:", accuracy_score(y_train, train_pred))
print("Validation Accuracy:", accuracy_score(y_val, val_pred))
print("Test Accuracy:", accuracy_score(y_test, test_pred))

print("\n--- Validation Classification Report ---")
print(classification_report(y_val, val_pred))

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

"""**الاداء العام للنموذج**
| المجموعة | الدقة (Accuracy) |
|--------|------------------|
| Training | 82.9% |
| Validation | 72.8% |
| Test | 72.7% |
**تحليل:**
- الفرق بين دقة التدريب ودقة التحقق/الاختبار يشير إلى Overfitting محدود
- تقارب دقة التحقق والاختبار يدل على أن النموذج يعمّم بشكل جيد ولا يحفظ البيانات فقط.

`Class-wise Performance:`
الفئات ذات العينات الكبيرة (مثل 1، 2، 3، 6، 8، 10، 11) أظهرت:
- Precision وRecall مرتفعين
- قيم F1-score جيدة (0.74 – 0.85)

الفئة 10 هي الأفضل أداء

F1 ≈ 0.85 في كل من Validation وTest
→ يدل على تمييز قوي للسمات النصية الخاصة بها.

`Impact of Class Imbalance:`

بعض الفئات ذات الدعم القليل جدا (مثل 7، 12، 14، 15) سجلت:

- Recall منخفض
- F1-score ضعيف (< 0.30)

رغم استخدام class_weight='balanced'، ما زال النموذج يعاني مع الفئات النادرة.

`Macro vs Weighted Average:`

- Weighted F1 ≈ 0.73
→ يعكس أداء جيدا على الفئات الأكثر شيوعًا.

- Macro F1 ≈ 0.59
→ يكشف التفاوت في الأداء بين الفئات، خاصة الفئات الصغيرة.

الفرق بينهما يؤكد أن عدم توازن البيانات يؤثر على التقييم الكلي.

` Validation vs Test Consistency:`

التشابه الكبير بين تقارير Validation وTest:

يدل على أن عملية التقسيم صحيحة

ولا يوجد تسريب بيانات (Data Leakage)

#Confusion matrix :
"""

cm_test = confusion_matrix(y_test, test_pred)
print(f"Confusion matrix for test data (Shape: {cm_test.shape})")

plt.figure(figsize=(15, 13))
sns.heatmap(cm_test,
            annot=False,
            fmt='d',
            cmap='Blues',
            cbar_kws={'label': 'Number of samples'},
            square=True)

plt.title('Confusion Matrix - LogisticRegression Model (Test Data)',
          fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Predicted Label', fontsize=14)
plt.ylabel('True Label', fontsize=14)
plt.tight_layout()
plt.show()

def calculate_class_accuracy(cm, class_names):
    class_accuracies = []

    for i, class_name in enumerate(class_names):
        correct = cm[i, i]
        total = cm[i, :].sum()
        accuracy = (correct / total * 100) if total > 0 else 0

        class_accuracies.append({
            'Class': class_name,
            'Accuracy_%': accuracy,
            'Correct': correct,
            'Total': total,
            'Errors': total - correct
        })

    accuracy_df = pd.DataFrame(class_accuracies)
    accuracy_df = accuracy_df.sort_values('Accuracy_%')

    return accuracy_df

accuracy_df = calculate_class_accuracy(cm_test, class_names)

low_accuracy_classes = accuracy_df[accuracy_df['Accuracy_%'] < 60]['Class'].tolist()
low_accuracy_indices = [np.where(class_names == cls)[0][0] for cls in low_accuracy_classes]

if low_accuracy_indices:
    cm_problematic = cm_test[low_accuracy_indices][:, low_accuracy_indices]

    plt.figure(figsize=(10, 8))
    sns.heatmap(cm_problematic,
                annot=True,
                fmt='d',
                cmap='Reds',
                xticklabels=low_accuracy_classes,
                yticklabels=low_accuracy_classes)

    plt.title('Confusion Matrix for Low-Accuracy Classes (< 60%)', fontsize=14, fontweight='bold')
    plt.xlabel('Predicted Label', fontsize=12)
    plt.ylabel('True Label', fontsize=12)
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

"""### 🔍 Hyperparameter Tuning (Logistic Regression)
في هذه المرحلة قمنا باستخدام `GridSearchCV` لاختيار أفضل معاملات (Hyperparameters)

المعاملات التي تم اختبارها:
- **C**: للتحكم بدرجة التنظيم (Regularization Strength)
- **penalty**: استخدمنا L2
- **solver**: جربنا `lbfgs` و `liblinea
"""

param_grid = {
    'C': [0.01, 0.1, 1, 5, 10],
    'penalty': ['l2'],
    'solver': ['lbfgs','liblinear']
}
grid = GridSearchCV(
    LogisticRegression(max_iter=3000),
    param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1 )

grid.fit(X_train_tfidf, y_train)
print("Best Params:", grid.best_params_)
best_log_reg = grid.best_estimator_
y_val_pred = best_log_reg.predict(X_val_tfidf)
print("Improved Validation Accuracy:", accuracy_score(y_val, y_val_pred))

"""النتيجة:
- أفضل إعدادات كانت:
  - `C = 5`
  - `penalty = 'l2'`
  - `solver = 'liblinear'`

###  Training Logistic Regression with Best Parameters

بعد تحديد أفضل المعاملات من خلال GridSearchCV،
قمنا بإعادة تدريب نموذج Logistic Regression باستخدام هذه القيم:
"""

logreg = LogisticRegression(
    C=5,
    penalty='l2',
    max_iter=300,
    class_weight='balanced',
    solver='liblinear',
)
logreg.fit(X_train_tfidf, y_train)
train_pred = logreg.predict(X_train_tfidf)
val_pred = logreg.predict(X_val_tfidf)
test_pred = logreg.predict(X_test_tfidf)

print("Train Accuracy:", accuracy_score(y_train, train_pred))
print("Validation Accuracy:", accuracy_score(y_val, val_pred))
print("Test Accuracy:", accuracy_score(y_test, test_pred))

print("\n--- Validation Classification Report ---")
print(classification_report(y_val, val_pred))

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

"""- نتائج الاختبار متقاربة جدًا مع نتائج التحقق،
  مما يؤكد قدرة النموذج على التعميم.
- الفئات الرئيسية حافظت على أداء مستقر:
  - الفئات 2، 3، 6، 8، 10، 11
- الفئات النادرة ما زالت تمثل التحدي الأكبر،
  خاصة من حيث Recall وF1-score.

المقاييس العامة:
- **Test Accuracy ≈ 73.7%**
- **Macro F1 ≈ 0.59**
- **Weighted F1 ≈ 0.73**

هذا يؤكد أن تحسين الأداء الإضافي
يتطلب نماذج أعمق أو تمثيلات لغوية أغنى.

###  Linear SVM Baseline

في هذه التجربة استخدمنا نموذج **Linear Support Vector Machine (LinearSVC)**  
مع تمثيل النصوص باستخدام **TF-IDF** ومعالجة عدم توازن الفئات عبر:
- `class_weight = 'balanced'`
"""

svm_clf = LinearSVC(C=1.0, class_weight='balanced')
svm_clf.fit(X_train_tfidf, y_train)
train_pred = svm_clf.predict(X_train_tfidf)
val_pred = svm_clf.predict(X_val_tfidf)
test_pred = svm_clf.predict(X_test_tfidf)

print("Train Accuracy:", accuracy_score(y_train, train_pred))
print("Validation Accuracy:", accuracy_score(y_val, val_pred))
print("Test Accuracy:", accuracy_score(y_test, test_pred))

print("\n--- Validation Report ---")
print(classification_report(y_val, val_pred))

print("\n--- Test Report ---")
print(classification_report(y_test, test_pred))

"""نلاحظ:
- دقة تدريب مرتفعة جدًا → تشير إلى ميل النموذج لحفظ بيانات التدريب.
- انخفاض واضح بين التدريب والتحقق/الاختبار → وجود **overfitting**
  - صعوبة في التمييز رغم استخدام `class_weight='balanced'`

###  Linear SVM with Hyperparameter Tuning
"""

param_grid_svm = {
    'C': [0.1, 0.5, 1, 2, 5, 10]}
svm_model = LinearSVC(class_weight='balanced')
grid_svm = GridSearchCV(
    svm_model,
    param_grid_svm,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

grid_svm.fit(X_train_tfidf, y_train)
print("Best Params:", grid_svm.best_params_)
best_svm = grid_svm.best_estimator_
val_pred = best_svm.predict(X_val_tfidf)
print("Improved Validation Accuracy:", accuracy_score(y_val, val_pred))

best_svm = grid_svm.best_estimator_

train_pred = best_svm.predict(X_train_tfidf)
val_pred = best_svm.predict(X_val_tfidf)
test_pred = best_svm.predict(X_test_tfidf)

print("Train Accuracy:", accuracy_score(y_train, train_pred))
print("Validation Accuracy:", accuracy_score(y_val, val_pred))
print("Test Accuracy:", accuracy_score(y_test, test_pred))

print("\n--- Validation Classification Report ---")
print(classification_report(y_val, val_pred))

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

"""- انخفاض دقة التدريب مقارنة بالـ baseline → تقليل overfitting
- تحسن طفيف لكن مستقر في دقة التحقق والاختبار
- تقارب Validation وTest يدل على **تحسن التعميم*

###  Naive Bayes Models Evaluation (TF-IDF Features)

في هذه المرحلة قمنا بتجربة نموذجين من عائلة Naive Bayes:
- Multinomial Naive Bayes (MNB)
- Complement Naive Bayes (CNB)
"""

def evaluate_nb_model(model, X_train, y_train, X_val, y_val, X_test, y_test):
    model.fit(X_train, y_train)
    y_pred_train = model.predict(X_train)
    y_pred_val   = model.predict(X_val)
    y_pred_test  = model.predict(X_test)

    print("===== TRAIN =====")
    print("Accuracy:", accuracy_score(y_train, y_pred_train))
    print(classification_report(y_train, y_pred_train))

    print("===== VALIDATION =====")
    print("Accuracy:", accuracy_score(y_val, y_pred_val))
    print(classification_report(y_val, y_pred_val))

    print("===== TEST =====")
    print("Accuracy:", accuracy_score(y_test, y_pred_test))
    print(classification_report(y_test, y_pred_test))


# Train Multinomial NB
print("\n================ MultinomialNB ================\n")
mnb = MultinomialNB()
evaluate_nb_model(mnb,
                  X_train_tfidf, y_train,
                  X_val_tfidf, y_val,
                  X_test_tfidf, y_test)


# Train Complement NB
print("\n================ ComplementNB ================\n")
cnb = ComplementNB()
evaluate_nb_model(cnb,
                  X_train_tfidf, y_train,
                  X_val_tfidf, y_val,
                  X_test_tfidf, y_test)

"""##  Multinomial Naive Bayes

**Performance Insights**
- النموذج يميل بشدة إلى الفئات الأكثر تكرارًا.
- العديد من الفئات (مثل 7، 12، 14، 15) حصلت على:
  - Recall = 0
  - F1-score = 0
- يظهر النموذج ضعفًا واضحًا في التعامل مع عدم توازن البيانات.
- MultinomialNB غير مناسب لهذا التصنيف متعدد الفئات مع عدم توازن كبير.
- لا يُنصح بالاعتماد عليه كنموذج نهائي.
##Complement Naive Bayes

 **Performance Insights**
- تحسن واضح مقارنة بـ MultinomialNB، خاصة مع الفئات غير المتوازنة.
- الفئات الكبيرة (1، 2، 3، 6، 8، 10، 11):
  - حققت F1-score بين **0.73 – 0.84**
- ما زالت الفئات النادرة تعاني من:
  - Recall منخفض جدًا
  - بعض الفئات لم يتم التنبؤ بها إطلاقًا.


### الخلاصة
- ComplementNB يتفوق بوضوح على MultinomialNB.
- مناسب كنموذج baseline سريع.
- لكنه لا يصل لأداء Logistic Regression أو SVM.

###  Complement Naive Bayes with Hyperparameter Tuning
"""

param_grid = {
    'alpha': [0.1, 0.3, 0.5, 1, 2, 3, 5],
    'norm': [True, False]
}

cnb_grid = GridSearchCV(
    ComplementNB(),
    param_grid,
    scoring='accuracy',
    cv=3,
    n_jobs=-1,
    verbose=1
)

cnb_grid.fit(X_train_tfidf, y_train)

print("Best Params:", cnb_grid.best_params_)

best_cnb = cnb_grid.best_estimator_

train_pred = best_cnb.predict(X_train_tfidf)
val_pred   = best_cnb.predict(X_val_tfidf)
test_pred  = best_cnb.predict(X_test_tfidf)

print("\n===== ACCURACY =====")
print("Train:", accuracy_score(y_train, train_pred))
print("Validation:", accuracy_score(y_val, val_pred))
print("Test:", accuracy_score(y_test, test_pred))

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

print("\n--- Validation Classification Report ---")
print(classification_report(y_val, val_pred))

"""- تحسن طفيف في Validation و Test مقارنة بالإعداد الافتراضي.
- الفجوة الصغيرة بين Train و Validation تشير إلى:
  - عدم وجود overfitting حاد
- ما زال النموذج يعاني مع الفئات النادرة.

###  Random Forest Classifier with Randomized Search
"""

rf_model = RandomForestClassifier(class_weight='balanced', n_jobs=-1)

param_dist = {
    'n_estimators': [100, 150],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt'],
}

random_search = RandomizedSearchCV(
    rf_model,
    param_distributions=param_dist,
    n_iter=5,
    cv=2,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1,
    random_state=42
)
random_search.fit(X_train_tfidf, y_train)
print("Best Params:", random_search.best_params_)
best_rf = random_search.best_estimator_

train_pred = best_rf.predict(X_train_tfidf)
val_pred = best_rf.predict(X_val_tfidf)
test_pred = best_rf.predict(X_test_tfidf)

print("\n===== ACCURACY =====")
print("Train Accuracy:", accuracy_score(y_train, train_pred))
print("Validation Accuracy:", accuracy_score(y_val, val_pred))
print("Test Accuracy:", accuracy_score(y_test, test_pred))

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

print("\n--- Validation Classification Report ---")
print(classification_report(y_val, val_pred))

"""- الأداء العام للنموذج منخفض مقارنة بنماذج خطية مثل:
  - Logistic Regression
  - Linear SVM
- الفجوة الصغيرة بين Train و Validation تشير إلى:
  - عدم وجود overfitting
  - لكن النموذج يعاني من underfitting
- Random Forest غير مناسب بشكل جيد لبيانات نصية عالية الأبعاد ومتناثرة مثل TF-IDF.

## الطريقة الثانية: Embedding + Deep Learning

تعتمد هذه الطريقة على تمثيل النصوص باستخدام Embedding Layer، حيث يتم تحويل كل كلمة إلى متجه عددي كثيف يعكس معناها وسياقها. بعد ذلك يتم تمرير تسلسل المتجهات إلى نموذج تعلم عميق مثل LSTM أو BiLSTM لاستخلاص العلاقات الزمنية بين الكلمات، ثم تصنيف النص باستخدام طبقة Softmax. تمتاز هذه الطريقة بقدرتها على فهم ترتيب الكلمات والعلاقات الدلالية بينها مقارنةً بالطرق التقليدية مثل TF-IDF.

###  تحضير البيانات النصية

في هذه المرحلة قمنا باستخراج النصوص من عمود `trimmed_question`
وتحويلها إلى نوع `string` لضمان التوافق مع أدوات المعالجة النصية.

بعد ذلك تم تحويل الوسوم (labels) من قيم نصية إلى قيم رقمية باستخدام
`LabelEncoder`
"""

X_train_text = train_df['trimmed_question'].astype(str)
X_val_text   = val_df['trimmed_question'].astype(str)
X_test_text  = test_df['trimmed_question'].astype(str)

y_train = train_df['label']
y_val   = val_df['label']
y_test  = test_df['label']

label_encoder = LabelEncoder()
y_train_enc = label_encoder.fit_transform(y_train)
y_val_enc   = label_encoder.transform(y_val)
y_test_enc  = label_encoder.transform(y_test)
num_classes = len(label_encoder.classes_)
print("Number of classes:", num_classes)

"""## Tokenization وتحويل النصوص إلى تسلسلات رقمية
تم استخدام `Tokenizer` لتحويل الكلمات إلى أرقام، مع تحديد:
- `max_words = 50000` لتحديد حجم القاموس
- استخدام رمز `<OOV>` للتعامل مع الكلمات غير المعروفة

بعد التدريب على بيانات التدريب فقط، ثم تحويل:
- بيانات التدريب
- بيانات التحقق
- بيانات الاختبار  
إلى تسلسلات رقمية تمثل كل كلمة برقم فريد.
"""

max_words = 50000
tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train_text)

X_train_seq = tokenizer.texts_to_sequences(X_train_text)
X_val_seq   = tokenizer.texts_to_sequences(X_val_text)
X_test_seq  = tokenizer.texts_to_sequences(X_test_text)

"""## Padding وتوحيد أطوال الجمل

نظرًا لاختلاف أطوال الأسئلة النصية، قمنا بتوحيد الطول باستخدام
`pad_sequences` بحيث يصبح طول كل تسلسل `100` كلمة.

تم اعتماد:
- `padding='post'` لإضافة الحشو في نهاية الجملة
- هذا يسهل على نموذج LSTM معالجة البيانات على دفعات ثابتة الشكل
"""

max_len = 80
X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=max_len,
    padding='post',
    truncating='post'
)

X_val_pad = pad_sequences(
    X_val_seq,
    maxlen=max_len,
    padding='post',
    truncating='post'
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=max_len,
    padding='post',
    truncating='post'
)

"""##بناء نموذج LSTM

"""

lengths = [len(seq) for seq in X_train_seq]
np.percentile(lengths, [50, 75, 90, 95, 99])
max_len = 80

num_classes = df['label'].nunique()
embedding_dim = 128

model_lstm = Sequential([
    Embedding(
        input_dim=max_words,
        output_dim=embedding_dim,
        input_length=max_len
    ),

    LSTM(128, return_sequences=False),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

model_lstm.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

"""### معالجة عدم توازن الفئات باستخدام Class Weights

"""

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights_dict = dict(zip(classes, class_weights))

history_lstm = model_lstm.fit(
    X_train_pad,
    y_train,
    validation_data=(X_val_pad, y_val),
    epochs=10,
    batch_size=64,
    class_weight=class_weights_dict
)

"""نلاحظ تحسنا تدريجيا في Training Accuracy من قيم منخفضة جدا في البداية إلى أكثر من 91% في نهاية التدريب.

Validation Accuracy ارتفعت تدريجيا أيضا، حيث وصلت إلى حوالي 60%.

بعد عدة عصور، بدأ Validation Loss بالازدياد رغم تحسن دقة التدريب، مما يشير إلى بداية حدوث Overfitting.
"""

test_loss, test_acc = model_lstm.evaluate(X_test_pad, y_test)
print("Test Accuracy:", test_acc)

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

"""# بناء نموذج BiLSTM

في هالخلية عم نبني نموذج BiLSTM لتصنيف النصوص.

النموذج بيستخدم Embedding Layer لتمثيل الكلمات، يلي بعدها يمررها Bidirectional LSTM لاستخلاص العلاقات الزمنية بين الكلمات، ومن ثم طبقات Dense وDropout لتقليل الإفراط في التعلم وتصنيف النصوص.
"""

model_bilstm = Sequential([
    Embedding(
        input_dim=max_words,
        output_dim=embedding_dim,
        input_length=max_len
    ),

    Bidirectional(LSTM(128)),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

model_bilstm.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

"""تدريب نموذج BiLSTM"""

history_bilstm = model_bilstm.fit(
    X_train_pad,
    y_train,
    validation_data=(X_val_pad, y_val),
    epochs=10,
    batch_size=64,
    class_weight=class_weights_dict
)

"""النموذج بدأ بدقة منخفضة جدا في البداية (≈18%) على التدريب ودقة منخفضة على التحقق (≈39%).

مع تقدم التدريب، يتحسن الأداء على كل من التدريب والتحقق، مما يدل على أن النموذج يتعلم التمثيل المناسب للنصوص.

على الرغم من تحسن الدقة التدريبية بشكل كبير (>96%)، دقة التحقق تصل إلى حوالي 64%، مما يشير إلى بعض الإفراط في التعلّم (overfitting).
"""

test_loss, test_acc = model_bilstm.evaluate(X_test_pad, y_test)
print("BiLSTM Test Accuracy:", test_acc)

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

"""دقة النموذج على مجموعة الاختبار حوالي 64.5%، وهو قريب من دقة التحقق مما يدل على ثبات أداء النموذج.

قيمة الخسارة على الاختبار مرتفعة نسبيًا (≈2.17)، مما يشير إلى أن النموذج يواجه صعوبة في بعض العينات

# بناء نموذج BiLSTM محسّن (BiLSTM Regularized)

هالخلية عم نبني نسخة محسّنة من نموذج BiLSTM لتقليل الإفراط في التعلم. التعديلات تشمل:

زيادة أبعاد الـ Embedding إلى 300

إضافة Dropout إضافية قبل وبعد الـ LSTM وDense layer لمقاومة الإفراط في التعلم.

طبقة Dense أكبر (128 وحدة) لتقوية قدرة النموذج على استخراج الميزات.
"""

model_bilstm_reg = Sequential([
    Embedding(
        input_dim=max_words,
        output_dim=300,
        input_length=max_len
    ),

    Dropout(0.3),
    Bidirectional(LSTM(128, return_sequences=False)),
    Dropout(0.4),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(num_classes, activation='softmax')
])

model_bilstm_reg.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

"""## إعداد Early Stopping

هنا نضيف EarlyStopping لإيقاف التدريب تلقائيا إذا لم يتحسن النموذج على بيانات التحقق لمدة معينة(3 epochs)، واستعادة أفضل الأوزان لتقليل الإفراط في التعلم.
"""

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True)

history_bilstm_reg = model_bilstm_reg.fit(
    X_train_pad, y_train,
    validation_data=(X_val_pad, y_val),
    epochs=20,
    batch_size=64,
    callbacks=[early_stopping])

"""النموذج بدأ بدقة منخفضة على الـ training (33%) ولكنه تحسن بسرعة خلال الـ epochs الأولى.

دقة التحقق (val_accuracy) وصلت إلى حوالي 69-70% في أول 3 epochs، وهذا يدل على أن النموذج تعلم تمثيلات قوية بسرعة.

بعد الـ epoch الثالث، الدقة على التحقق لم تتحسن، مما أدى إلى توقف التدريب مبكرًا بواسطة EarlyStopping.

هذا يوضح أن الـ BiLSTM المحسّن مع Dropout وEmbedding أكبر قادر على تعلم ميزات جيدة بسرعة مع مقاومة الإفراط في التعلم.
"""

test_loss, test_acc = model_bilstm_reg.evaluate(X_test_pad, y_test)
print("Improved BiLSTM Test Accuracy:", test_acc)

"""- دقة الاختبار بلغت حوالي 69.6% وهي أفضل من نماذج LSTM وBiLSTM السابقة بدون تحسينات.

- هذا يشير إلى أن التعديلات (زيادة حجم الـ Embedding، Dropout إضافية، Dense أكبر، واستخدام EarlyStopping) ساعدت على تحسين قدرة النموذج على التعميم وتقليل الإفراط في التعلم.

- الأداء المتوازن بين التدريب والتحقق يشير إلى أن النموذج تعلم تمثيلات جيدة للنصوص ولم يبالغ في حفظ بيانات التدريب فقط.
"""

test_pred_prob = model_bilstm_reg.predict(X_test_pad)
test_pred = np.argmax(test_pred_prob, axis=1)
print("\nClassification Report on Test Set:")
print(classification_report(y_test, test_pred))

"""## تدريب نموذج BiLSTM مع استخدام أوزان الفئات (Class Weights)"""

history_bilstm = model_bilstm.fit(
    X_train_pad,
    y_train,
    validation_data=(X_val_pad, y_val),
    epochs=20,
    batch_size=64,
    class_weight=class_weights_dict,
    callbacks=[early_stopping]
)

"""- نلاحظ أن دقة التدريب مرتفعة جدًا منذ البداية (≈97%)، ما يدل على أن النموذج قادر على حفظ بيانات التدريب بسرعة.

- بالمقابل، دقة التحقق (val_accuracy) بقيت بحدود 64–65% ولم تتحسن بشكل واضح.

- ارتفاع val_loss مع كل epoch يشير إلى overfitting واضح رغم استخدام class weights وEarlyStopping.

"""

test_loss, test_acc = model_bilstm.evaluate(X_test_pad, y_test)
print("Improved BiLSTM with class-weight Test Accuracy:", test_acc)

print("\n--- Test Classification Report ---")
print(classification_report(y_test, test_pred))

"""دقة الاختبار بلغت حوالي 64.4%، وهي أقل من دقة نموذج BiLSTM المحسّن مع EarlyStopping.

هذا يؤكد أن:

استخدام class_weight بدون تنظيم إضافي قوي قد يؤدي إلى overfitting.

النموذج المحسّن السابق (Embedding أكبر + Dropout أقوى + EarlyStopping) كان أكثر استقرارًا وأفضل في التعميم.

# CNN

في هذه الخلية نقوم ببناء نموذج Convolutional Neural Network (CNN) لمعالجة النصوص.
تعتمد الفكرة على استخدام Embedding Layer لتحويل الكلمات إلى متجهات عددية، ثم تطبيق Conv1D لاستخلاص الأنماط المحلية (n-grams) داخل الجمل، مثل العبارات أو الكلمات المتجاورة المهمة للتصنيف.
بعد ذلك نستخدم Global Max Pooling لاختيار أهم الخصائص المستخرجة، ثم طبقات Fully Connected لإجراء التصنيف النهائي.
"""

MAX_WORDS = 50000
model_cnn = Sequential([
    Embedding(
        input_dim=MAX_WORDS,
        output_dim=128,
        input_length=max_len
    ),

    Conv1D(filters=128, kernel_size=5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

model_cnn.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_cnn = model_cnn.fit(
    X_train_pad, y_train,
    validation_data=(X_val_pad, y_val),
    epochs=20,
    batch_size=32,
    callbacks=[early_stopping],
    verbose=1
)

"""نلاحظ ارتفاعًا سريعًا في دقة التدريب حتى وصلت إلى أكثر من 97%.

دقة التحقق وصلت إلى حوالي 71.7% ثم بدأت بالانخفاض.

هذا السلوك يدل على أن النموذج:

تعلّم الأنماط بسرعة.

لكنه بدأ يعاني من overfitting بعد عدة epochs.
"""

test_loss, test_acc = model_cnn.evaluate(X_test_pad, y_test, verbose=1)
print("CNN Test Accuracy:", test_acc)
y_pred_probs = model_cnn.predict(X_test_pad)
y_pred = np.argmax(y_pred_probs, axis=1)
print(classification_report(y_test, y_pred))

"""الأداء العام أفضل من:

LSTM

BiLSTM التقليدي

وقريب جدًا من أفضل نموذج BiLSTM محسّن.

تحليل تقرير التصنيف:

- الفئات الكبيرة (مثل 1، 2، 10، 11) حققت أداءً جيدًا من حيث precision وrecall.

- بعض الفئات النادرة (مثل 7، 12، 14، 15) لم يتم التنبؤ بها تقريبًا:

مما أدى إلى قيم precision = 0.

## بناء نموذج CNN مع Class Weights

في هذه الخلية نقوم ببناء نموذج CNN
 مشابه للنموذج السابق، ولكن الهدف هنا هو تحسين أداء النموذج على الفئات غير المتوازنة لاحقًا باستخدام class weights أثناء التدريب.
"""

model_cnn_cw = Sequential([
    Embedding(input_dim=MAX_WORDS, output_dim=128, input_length=max_len),
    Conv1D(128, 5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])
model_cnn_cw.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_cnn_cw = model_cnn_cw.fit(
    X_train_pad, y_train,
    validation_data=(X_val_pad, y_val),
    epochs=20,
    batch_size=64,
    class_weight=class_weights_dict,
    callbacks=[early_stopping]
)

"""دقة التدريب ارتفعت بسرعة ووصلت إلى أكثر من 97%.

دقة التحقق استقرت حول 68%.

الفجوة بين دقة التدريب والتحقق تشير إلى وجود overfitting، لكن أقل حدّة على الفئات النادرة مقارنة بنموذج CNN بدون class weights.
"""

test_loss, test_acc = model_cnn_cw.evaluate(X_test_pad, y_test)
print("CNN + Class Weights Test Accuracy:", test_acc)
y_pred = np.argmax(model_cnn_cw.predict(X_test_pad), axis=1)

print(classification_report(y_test, y_pred, digits=2))

"""Test Accuracy ≈ 66.8%

أقل من CNN بدون class weights (~70%)

وأقل من BiLSTM المحسّن (~69.6%)

 **تحليل الفئات النادرة:**

مقارنةً بـ CNN بدون class weights:

تحسن واضح في recall للفئات الصغيرة مثل:

الفئة 7
, الفئة 12
 , الفئة 14
 , الفئة 15

لم تعد بعض الفئات مهملة بالكامل (recall = 0)، وهو تحسن مهم.

 **المقايضة (Trade-off):**

تحسن أداء الفئات النادرة -

انخفاض الدقة العامة للنموذج -

##  Multi- Kernel CNN
"""

MAX_LEN = 100
MAX_WORDS= 50000
X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding='post', truncating='post')
X_val_pad   = pad_sequences(X_val_seq,   maxlen=MAX_LEN, padding='post', truncating='post')
X_test_pad  = pad_sequences(X_test_seq,  maxlen=MAX_LEN, padding='post', truncating='post')

inputs = Input(shape=(MAX_LEN,))

x = Embedding(
    input_dim=MAX_WORDS,
    output_dim=128,
    input_length=MAX_LEN
)(inputs)

x = SpatialDropout1D(0.3)(x)

conv_3 = Conv1D(128, 3, activation='relu')(x)
conv_4 = Conv1D(128, 4, activation='relu')(x)
conv_5 = Conv1D(128, 5, activation='relu')(x)

pool_3 = GlobalMaxPooling1D()(conv_3)
pool_4 = GlobalMaxPooling1D()(conv_4)
pool_5 = GlobalMaxPooling1D()(conv_5)

x = Concatenate()([pool_3, pool_4, pool_5])

x = BatchNormalization()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)

outputs = Dense(num_classes, activation='softmax')(x)

model_cnn_adv = Model(inputs, outputs)

model_cnn_adv.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Tokenizer vocab size:", len(tokenizer.word_index))

print("Max value in X_train_pad:", np.max(X_train_pad))
print("Max value in X_val_pad:", np.max(X_val_pad))
print("Max value in X_test_pad:", np.max(X_test_pad))

vocab_size = 50000

X_train_pad = np.clip(X_train_pad, 0, vocab_size - 1)
X_val_pad = np.clip(X_val_pad, 0, vocab_size - 1)
X_test_pad = np.clip(X_test_pad, 0, vocab_size - 1)

print(f"تم تقليم البيانات. القيم الآن بين 0 و{vocab_size-1}")

history_cnn_adv = model_cnn_adv.fit(
    X_train_pad,
    y_train,
    validation_data=(X_val_pad, y_val),
    epochs=20,
    batch_size=64,
    callbacks=[early_stopping],
    verbose=1
)

"""أثناء التدريب

Training accuracy ارتفعت بسرعة ووصلت ≈ 91%

Validation accuracy توقفت تقريبًا بين 70% – 71%

Validation loss بدأ يرتفع بعد Epoch 2–3

📌 الاستنتاج هنا

النموذج يتعلّم بسرعة من بيانات التدريب، لكن يبدأ overfitting مبكّرًا
(يعني حفظ التدريب أكثر من التعميم).
"""

test_loss, test_acc = model_cnn_adv.evaluate(X_test_pad, y_test)
print("Advanced CNN Test Accuracy:", test_acc)
y_pred = model_cnn_adv.predict(X_test_pad)
y_pred = y_pred.argmax(axis=1)
print(classification_report(y_test, y_pred, digits=2))

"""Test Accuracy ≈ 70.45%

هذه أعلى دقة وصلتي لها مع CNN لحد الآن
الفئات الكبيرة (مثل 1، 2، 3، 6، 10، 11):

Precision و Recall جيدين

F1-score مرتفع نسبيًا

النموذج ممتاز في الفئات ذات العينات الكثيرة
فئات مثل: 7، 12، 14

Precision = 0

Recall = 0

يعني:

النموذج لم يتنبأ ولا مرة بهذه الفئات

## 🔹 نموذج CNN مع FastText Embeddings

في هذه التجربة نستخدم تمثيلات الكلمات الجاهزة **FastText العربية (cc.ar.300.vec)** بدل تعلّم الـ embeddings من الصفر.  
FastText يتميز بقدرته على تمثيل الكلمات النادرة والمشتقة لغويًا بشكل أفضل، وهو مناسب جدًا للغة العربية.

### خطوات العمل:
1. تحميل متجهات FastText العربية مسبقة التدريب (300 بعد).
2. بناء `embedding_matrix` بحيث:
   - كل كلمة في `tokenizer.word_index` تأخذ المتجه المقابل لها إن وُجد.
   - الكلمات غير الموجودة في FastText تأخذ متجه صفري.
3. استخدام طبقة `Embedding` بالأوزان الجاهزة مع `trainable=False` للحفاظ على المعرفة اللغوية.
4. تمرير الـ embeddings إلى طبقة **Conv1D** لاستخراج الأنماط المحلية (n-grams).
5. استخدام **GlobalMaxPooling1D** لاختيار أهم الميزات.
6. طبقات Dense لإجراء التصنيف النهائي.
"""

!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ar.300.vec.gz
!gunzip cc.ar.300.vec.gz

EMBEDDING_DIM = 300
embedding_index = {}

with open("cc.ar.300.vec", encoding="utf-8") as f:
    for line in f:
        values = line.rstrip().split(" ")
        word = values[0]
        vector = np.asarray(values[1:], dtype="float32")
        embedding_index[word] = vector

print("عدد الكلمات المحملة:", len(embedding_index))

word_index = tokenizer.word_index
num_words = min(MAX_WORDS, len(word_index) + 1)

embedding_matrix = np.zeros((num_words, EMBEDDING_DIM))

for word, i in word_index.items():
    if i >= num_words:
        continue
    vector = embedding_index.get(word)
    if vector is not None:
        embedding_matrix[i] = vector

model_cnn_ft = Sequential([
    Embedding(
        input_dim=num_words,
        output_dim=EMBEDDING_DIM,
        weights=[embedding_matrix],
        input_length=MAX_LEN,
        trainable=False   # مهم
    ),
    Conv1D(128, 5, activation='relu'),
    GlobalMaxPooling1D(),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dense(16, activation='softmax')
])

model_cnn_ft.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history_cnn_ft = model_cnn_ft.fit(
    X_train_pad, y_train,
    validation_data=(X_val_pad, y_val),
    epochs=10,
    batch_size=64
)

test_loss, test_acc = model_cnn_ft.evaluate(X_test_pad, y_test)
print("CNN + FastText Test Accuracy:", test_acc)
y_pred = model_cnn_ft.predict(X_test_pad)
y_pred_classes = y_pred.argmax(axis=1)

print(classification_report(y_test, y_pred_classes))

cm = confusion_matrix(y_test, y_pred_classes)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    cmap="Blues",
    xticklabels=range(num_classes),
    yticklabels=range(num_classes),
    annot=False
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - CNN with FastText Embeddings")
plt.show()

"""###  أداء التدريب والتحقق (Training / Validation)
- بدأ النموذج بدقة تدريب منخفضة (~33%)، وهو أمر طبيعي عند استخدام embeddings ثابتة.
- ارتفعت دقة التحقق بسرعة لتصل إلى حوالي **69%**.
- الفجوة بين دقة التدريب والتحقق صغيرة → **لا يوجد overfitting واضح**.
- ثبات `val_loss` في المراحل الأخيرة يدل على وصول النموذج إلى حدوده الحالية.

###  أداء الاختبار (Test Set)
- **Test Accuracy ≈ 68.5%**
- الأداء قريب جدًا من دقة التحقق، وهذا مؤشر جيد على التعميم.

### تحليل تقرير التصنيف (Classification Report)
- الفئات ذات الدعم الكبير (مثل 1، 2، 10، 11) حققت:
  - Precision و Recall مرتفعين
  - F1-score جيد (≈ 0.7 – 0.8)
- الفئات ذات العينات القليلة (مثل 7، 12، 14):
  - Recall ضعيف أو صفر
  - النموذج لم يتعلم تمثيلها جيدًا بسبب **عدم توازن البيانات**

###  Macro vs Weighted Average
- **Macro Avg ≈ 0.48**
  - يتأثر بالفئات الصغيرة جدًا
- **Weighted Avg ≈ 0.67**
  - يعطي صورة أدق عن الأداء الحقيقي على البيانات

## Multi-Kernel CNN +FastText
"""

inputs = Input(shape=(MAX_LEN,))

embedding = Embedding(
    input_dim=num_words,
    output_dim=300,
    weights=[embedding_matrix],
    input_length=MAX_LEN,
    trainable=False
)(inputs)

x = SpatialDropout1D(0.3)(embedding)

# Multi-Kernel CNN
conv_3 = Conv1D(128, 3, activation='relu', padding='valid')(x)
conv_4 = Conv1D(128, 4, activation='relu', padding='valid')(x)
conv_5 = Conv1D(128, 5, activation='relu', padding='valid')(x)

pool_3 = GlobalMaxPooling1D()(conv_3)
pool_4 = GlobalMaxPooling1D()(conv_4)
pool_5 = GlobalMaxPooling1D()(conv_5)

x = Concatenate()([pool_3, pool_4, pool_5])

x = BatchNormalization()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)

outputs = Dense(num_classes, activation='softmax')(x)

model_mk_ft = Model(inputs, outputs)

model_mk_ft.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

history_mk_ft = model_mk_ft.fit(
    X_train_pad,
    y_train,
    validation_data=(X_val_pad, y_val),
    epochs=15,
    batch_size=64,
    callbacks=[early_stopping],
    verbose=1
)

test_loss, test_acc = model_mk_ft.evaluate(X_test_pad, y_test, verbose=0)
print("Multi-Kernel + FastText Test Accuracy:", test_acc)
y_pred = model_mk_ft.predict(X_test_pad)
y_pred_classes = y_pred.argmax(axis=1)

print(classification_report(y_test, y_pred_classes, zero_division=0))

"""### أداء التدريب والتحقق (Training / Validation)
- بدأ النموذج بدقة تدريب حوالي 71.04% في epoch 1، وارتفعت تدريجيًا لتصل إلى 74.47% في epoch 4.
- دقة التحقق كانت ثابتة حول 69% مع بعض التقلبات، مما يدل على أن النموذج لم يتعلم بشكل كافٍ لتحسين الأداء على مجموعة التحقق.
- الفجوة بين دقة التدريب والتحقق صغيرة نسبيًا، مما يشير إلى عدم وجود overfitting واضح.
- ثبات val_loss في المراحل الأخيرة يدل على وصول النموذج إلى حدوده الحالية.

### أداء الاختبار (Test Set)
- Test Accuracy ≈ 68.39%
- الأداء قريب جدًا من دقة التحقق، وهذا مؤشر جيد على قدرة النموذج على التعميم.

### تحليل تقرير التصنيف (Classification Report)
- الفئات ذات الدعم الكبير (مثل 1، 2، 10، 11) حققت:
  - Precision و Recall مرتفعين
  - F1-score جيد (≈ 0.7 – 0.8)
- الفئات ذات العينات القليلة (مثل 7، 12، 14):
  - Recall ضعيف أو صفر
  - النموذج لم يتعلم تمثيلها جيدًا بسبب عدم توازن البيانات.

### Macro vs Weighted Average
- Macro Avg ≈ 0.52
  - يتأثر بالفئات الصغيرة جدًا.
- Weighted Avg ≈ 0.66
  - يعطي صورة أدق عن الأداء الحقيقي على البيانات.

#الطريقة الثالثة
"""

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score

train_ds = Dataset.from_pandas(train_df[['trimmed_question', 'label']])
val_ds   = Dataset.from_pandas(val_df[['trimmed_question', 'label']])
test_ds  = Dataset.from_pandas(test_df[['trimmed_question', 'label']])

label_encoder = LabelEncoder()

train_labels = label_encoder.fit_transform(train_df['label'])
val_labels   = label_encoder.transform(val_df['label'])
test_labels  = label_encoder.transform(test_df['label'])

train_ds = train_ds.map(lambda x, i: {'label': train_labels[i]}, with_indices=True)
val_ds   = val_ds.map(lambda x, i: {'label': val_labels[i]}, with_indices=True)
test_ds  = test_ds.map(lambda x, i: {'label': test_labels[i]}, with_indices=True)

num_labels = len(label_encoder.classes_)
print("Number of classes:", num_labels)

model_name = "aubmindlab/bert-base-arabertv2"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels
)

"""**AraBERT v2:** نموذج BERT مدرب على نصوص عربية

**Tokenizer:** يحول النص إلى أرقام (Token IDs) يفهمها النموذج

**AutoModelForSequenceClassification:** نسخة من النموذج مُهيأة للتصنيف
"""

def tokenize(batch):
    return tokenizer(
        batch["trimmed_question"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_ds = train_ds.map(tokenize, batched=True)
val_ds   = val_ds.map(tokenize, batched=True)
test_ds  = test_ds.map(tokenize, batched=True)

"""
- **المدخلات**: تأخذ الدالة tokenize دفعة من البيانات (batch) تحتوي على عمود يسمى "trimmed_question".
- **التوكنيزر**: يتم استخدام tokenizer لتحويل النصوص إلى تمثيل عددي يمكن للنموذج فهمه.
- **المعلمات**:
  - padding="max_length": يضمن أن جميع التوكنات تكون بنفس الطول (128 توكن في هذه الحالة) عن طريق إضافة padding.
  - truncation=True: يقوم بقص النصوص التي تتجاوز الطول الأقصى المحدد (128 توكن).
  - max_length=128: يحدد الطول الأقصى للتوكنات.


"""

train_ds.set_format("torch", columns=["input_ids", "attention_mask", "label"])
val_ds.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_ds.set_format("torch", columns=["input_ids", "attention_mask", "label"])

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    acc = accuracy_score(labels, preds)
    f1  = f1_score(labels, preds, average="weighted")

    return {
        "accuracy": acc,
        "f1": f1
    }

"""## دالة compute_metrics

تقوم دالة compute_metrics بحساب دقتين للنموذج: الدقة ودرجة F1


## المخرجات
- **الدقة**: نسبة التوقعات الصحيحة.
- **درجة F1**: مقياس يوازن بين الدقة والاسترجاع.


"""

training_args = TrainingArguments(
    output_dir="./arabert-cpu",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=100,
    report_to="none",
    load_best_model_at_end=True,
    metric_for_best_model="eval_f1",
    greater_is_better=True
)

"""
- **حفظ النموذج**: سيتم حفظ النموذج في مجلد محدد بعد كل فترة تدريب.
- **التقييم**: سيتم تقييم النموذج بعد كل فترة تدريب.
- **معدل التعلم**: قيمة صغيرة للتحكم في سرعة التعلم.
- **حجم الدفعة**: عدد العينات المعالجة في وقت واحد أثناء التدريب والتقييم.
- **عدد الفترات**: سيتم تدريب النموذج لثلاث فترات.
- **الانحدار**: يستخدم لتقليل الإفراط في التكيف.
- **تسجيل المعلومات**: سيتم تسجيل المعلومات كل 100 خطوة.
- **اختيار أفضل نموذج**: سيتم تحميل النموذج الأفضل بناءً على درجة F1.
"""

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=1)]
)

"""
- **model**: النموذج الذي سيتم تدريبه.
- **args**: معايير التدريب.
- **train_dataset**: البيانات المستخدمة لتدريب النموذج.
- **eval_dataset**: البيانات المستخدمة لتقييم النموذج.
- **tokenizer**: الأداة المستخدمة لتحويل النصوص إلى تنسيق يمكن للنموذج فهمه.
- **compute_metrics**: دالة لحساب الأداء.
- **callbacks**: قائمة من callbacks، مثل EarlyStoppingCallback، لإدارة عملية التدريب.
"""

trainer.train()

test_results = trainer.evaluate(test_ds)
print(test_results)

"""### أداء التدريب والتحقق (Training / Validation)
- بدأ النموذج بدقة تدريب حوالي 74.12% في epoch 1، وارتفعت تدريجيًا لتصل إلى 76.63% في epoch 3.
- دقة التحقق كانت ثابتة حول 75.64% مع بعض التقلبات، مما يدل على أن النموذج قد بدأ في التعلم ولكنه لا يزال يحتاج إلى تحسين.
- الفجوة بين دقة التدريب والتحقق صغيرة نسبيًا، مما يشير إلى عدم وجود overfitting واضح.
- ثبات val_loss في المراحل الأخيرة يدل على وصول النموذج إلى حدوده الحالية.

### أداء الاختبار (Test Set)
- Test Accuracy ≈ 75.64%
- الأداء قريب جدًا من دقة التحقق، وهذا مؤشر جيد على قدرة النموذج على التعميم.

### Macro vs Weighted Average
- Macro Avg ≈ 0.70
  - يتأثر بالفئات الصغيرة جدًا.
- Weighted Avg ≈ 0.75
  - يعطي صورة أدق عن الأداء الحقيقي على البيانات.

#جدول مقارنة نماذج التصنيف

| النموذج                       | الدقة (Train) | الدقة (Validation) | الدقة (Test) | F1-Score (Macro Avg) | F1-Score (Weighted Avg) |
|-------------------------------|---------------|---------------------|--------------|-----------------------|--------------------------|
| Logistic Regression            | 82.89%        | 72.78%              | 72.67%       | 0.59                  | 0.73                     |
| Logistic Regression المحسن     | 93.67%        | 73.72%              | 73.74%       | 0.58                  | 0.73                     |
| SVM                           | 98.66%        | 73.46%              | 72.79%       | 0.58                  | 0.73                     |
| SVM المحسن                    | 95.83%        | 74.01%              | 73.79%       | 0.59                  | 0.74                     |
| MultinomialNB                 | 68.92%        | 64.61%              | 63.63%       | 0.34                  | 0.58                     |
| ComplementNB                   | 77.99%        | 72.50%              | 71.83%       | 0.49                  | 0.69                     |
| ComplementNB المحسن            | 79.88%        | 73.08%              | 72.72%       | 0.51                  | 0.71                     |
| Random Forest                  | 63.16%        | 61.13%              | 59.88%       | 0.47                  | 0.61                     |
| LSTM                          | 87.93%        | 59.43%              | 58.61%       | 0.47                  | 0.61                     |
| BiLSTM                        | 95.60%        | 64.28%              | 64.12%       | 0.47                  | 0.61                     |
| BiLSTM Regularized محسن       | 91.18%        | 66.44%              | 69.77%       | 0.45                  | 0.67                     |
| BiLSTM with Class Weights     | 98.61%        | 64.41%              | 62.25%       | 0.45                  | 0.67                     |
| CNN                           | 97.29%        | 69.23%              | 70.93%       | 0.48                  | 0.69                     |
| CNN + Class Weights           | 94.89%        | 68.68%              | 66.26%       | 0.52                  | 0.67                     |
| Multi-Kernel CNN              | 93.60%        | 69.95%              | 70.87%       | 0.50                  | 0.70                     |
| CNN + FastText                | 79.02%        | 69.41%              | 67.60%       | 0.48                  | 0.66                     |
| Multi-Kernel CNN + FastText   | 74.47%        | 69.05%              | 68.39%       | 0.47                  | 0.66                     |
| AraBERT v2                    | 87.12%      | 76.63%              | 75.64%       | 0.75                | 0.75                     |

#  أفضل نموذج: AraBERT v2

1. **الأداء الأعلى مطلقاً:**
   - **دقة الاختبار:** 75.64% (+1.85% عن ثاني أفضل نموذج)
   - **F1-Score:** 0.747 (أعلى توازن بين Precision و Recall)
   - **دقة التحقق:** 76.63% (أفضل تعميم)

2. **أسباب التفوق التقنية:**
   - **مدرب مسبقاً على العربية:** AraBERT مُدرب على 8.3 مليار كلمة عربية.
   - **فهم السياق:** يستخدم Transformers لفهم العلاقات بين الكلمات.
   - **تمثيل كلمات أفضل:** WordPiece tokenization للعربية.

3. **تحليل أداء التدريب:**
   | Epoch | Training Loss | Validation Accuracy | التحسن |
   |-------|---------------|---------------------|--------|
   | 1     | 0.995         | 74.12%              | -      |
   | 2     | 0.850         | 75.98%              | +1.86% |
   | 3     | 0.636         | 76.63%              | +0.65% |

4. **التعميم الممتاز:**
   - **فارق طفيف:** 76.63% (تحقق) → 75.64% (اختبار) = فارق 0.99% فقط.
   - **مؤشر:** النموذج يتعمم بشكل ممتاز على بيانات جديدة.
"""



